Improvements for the OAI-PMH Server.
vufind-org/vufind pull request #1237
Opened 2018-10-03 14:04 UTC by EreMaijala

- Use cursorMark instead of deep paging with Solr
- Make it possible to override the Server class
- Ignore records that cannot be returned in the requested format

cursorMark is the most important one, since deep paging cannot be used with large and/or sharded indexes. I've tried to make it generic enough that the implementation could be used with other sources too.

I believe that ignoring records that cannot be returned is the proper way to handle repositories with several metadata formats.

2018-10-03 15:00 UTC, demiankatz requested changes
Thanks for this! I've found a few issues that I think need to be addressed based on a code review... once you've had a chance to look at those, let me know, and I'll proceed with some hands-on testing to confirm that things are working as expected.

Whatever happens, I think we'll want to hold off on merging this until we begin work on 6.0, since this is a backward-breaking change... but I don't think that's very far off, with the Summit coming up in a couple of weeks, and not much on the slate for 5.1.

2018-10-04 07:33 UTC, EreMaijala commented on module/VuFind/src/VuFind/Search/Base/Results.php
> +    protected $startRecordOffset = null;
Okay, I'll revert to Solr-specific implementation.

2018-10-04 07:34 UTC, EreMaijala commented on module/VuFind/src/VuFind/OAI/Server.php
>          if ($currentCursor >= $deletedCount) {
I'll verify and fix as needed.

2018-10-04 08:37 UTC, EreMaijala commented
@demiankatz  Thanks for the review, all observations were spot on. They should now be addressed.

2018-10-04 17:07 UTC, demiankatz commented on module/VuFind/src/VuFind/OAI/Server.php
> +                continue;
If we continue here, is the fact that we're not incrementing $currentCursor as a result going to throw anything off? Seems like we might get duplicate or unexpected results....

2018-10-04 17:08 UTC, demiankatz commented
@EreMaijala, thanks for the fixes. I just added one new comment regarding the skipping of unsupported metadata records.

2018-10-05 14:11 UTC, EreMaijala commented
The skipping should be fixed now. 

It would be neat if we had record type indexed and mapping that would tell which types are available in the requested format so that skipping could be avoided altogether.

2018-10-31 20:42 UTC, demiankatz commented
Regarding indexing of record type, see #1260, which upgrades the recordtype field to record_format for consistency with the authority index (as suggested in my earlier comment). Hopefully we can merge this shortly after we begin work on the 6.0 release and can then take advantage of it here.

2019-02-04 19:52 UTC, demiankatz approved these changes

2019-02-04 19:54 UTC, merged

2019-02-04 19:55 UTC, demiankatz commented
@EreMaijala, this seems to be working well now, so I have merged it. I realize there is some open discussion about making better use of the record_format field after #1260 is merged, but I think it's just as well to deal with that in a separate PR if/when the time comes to work on it.