[VUFIND-1434] Change UrlQueryHelper::setDefaultParameter override default to false
vufind-org/vufind pull request #2015
Opened 2021-07-06 17:40 UTC by demiankatz

TODO
- [ ] Test everything
- [ ] Note change in changelog
- [ ] Resolve [VUFIND-1434](https://vufind.org/jira/browse/VUFIND-1434) when merging

2021-07-06 17:48 UTC, demiankatz commented
This is a follow-up to #1729. Unfortunately, I can't remember all of the details of that work at this point. It definitely seems to make more sense for the $forceOverride parameter to default to false; what I'm less sure about is whether any of the existing calls to setDefaultParameter now need to be changed to explicitly set the $forceOverride parameter to true, or if the new default behavior is equally appropriate. I'll start by running the full test suite to see if anything fails with just the initial change of the default, but I suspect there are some relevant edge cases that don't have test coverage, so this is going to require some additional hands-on testing (and perhaps the creation of some new tests). @EreMaijala, is this fresher in your mind than in mine? Do you have any thoughts? In any case, I'll report back with more details once tests finish running.

2021-07-06 17:57 UTC, demiankatz commented
All existing tests are passing... so the question is if there are edge cases that need to be covered.

2021-07-07 07:29 UTC, EreMaijala requested changes
I think the "if it is not already defined." part of the method doc needs to be changed as well.

2021-07-07 07:31 UTC, EreMaijala approved these changes

2021-07-07 15:48 UTC, merged