improve format detection for electronic integrating resources
vufind-org/vufind pull request #2408
Opened 2022-04-22 21:54 UTC by eocarragain

Another format tweak to allow for more specific forms of "OnlineIntegratingResource", starting with 'Websites'

Context:

- Vufind currently classifies any electronic (007/00=c) integrating resource (ldr/07=i) as "OnlineIntegratingResource" and ultimately mapped to "Database"
- 008/21 can allow us to be more specific here
- e.g. this initial patch handles blogs and websites (an NLI use-case), but more can be added

_Note: this commit also changes the "serial" switch case under getFormatFromBibLevel() to allow for rare edge-cases where the ldr/07=s (serial) but no 008 is present (these will still get mapped to 'Serial')_

2022-04-23 11:20 UTC, demiankatz requested changes
Thanks again for the ongoing improvements here, @eocarragain; the logic looks sound to me! Just two comments: a near-trivial formatting issue (see below) and the fact that you should add `Website = Website` to en.ini (and ga.ini and others, if you're able to provide translations you're confident in), since this adds a new format string, and those need to be translated.

2022-04-23 11:20 UTC, demiankatz commented on import/translation_maps/format_map.properties
> +Website             = Website
It would probably be good to add an end-of-file line break to all of the properties files just for consistency.

2022-04-24 19:41 UTC, eocarragain commented
thanks for reviewing @demiankatz . Those changes are committed now. cheers

2022-04-25 15:28 UTC, demiankatz approved these changes

2022-04-25 15:28 UTC, demiankatz commented
Thanks, @eocarragain -- looks great. Merging now!

2022-04-25 15:28 UTC, merged