Simplify the way "edit list" title is determined.
vufind-org/vufind pull request #2418
Opened 2022-05-04 16:52 UTC by demiankatz

This addresses a problem discovered while testing #2417: in PostgreSQL, new rows fetched from the database come with the ID pre-populated from the sequence, even if they are never saved. This interferes with correctly differentiating between "create row" and "edit row" titles. Fortunately, an existing flag offers an easier way to do this correctly.

Note that the underlying cause of the problem may still be a problem, since hitting "create list" repeatedly exhausts IDs unnecessarily. However, I'm not going to worry too much about that right now, since I'm hopeful that switching everything to Doctrine will likely change the situation anyway (see #2233).

2022-05-09 06:38 UTC, EreMaijala approved these changes

2022-05-09 06:39 UTC, EreMaijala requested changes
The change is good, but should https://github.com/vufind-org/vufind/blob/ea04a81dcd215a053f1ae1af57984e7377533402/themes/bootstrap3/templates/myresearch/editlist.phtml#L22 be changed as well?

2022-05-10 20:27 UTC, demiankatz commented
Good catch, @EreMaijala -- I've made the suggested edit and re-run tests in both MySQL and PostgreSQL. I think all is well now, but I'll await your approval before merging.

2022-05-11 06:06 UTC, EreMaijala approved these changes

2022-05-11 12:58 UTC, merged