Do not suggest using AggressiveOpts; it is deprecated.
vufind-org/vufind pull request #2428
Opened 2022-05-10 16:52 UTC by demiankatz

Some comments in import-marc scripts suggested possibly using AggressiveOpts, but it is now deprecated; see: https://dzone.com/articles/jdk-13-what-is-aggressiveopts for details. This PR simply removes the obsolete suggestion.

2022-05-10 16:53 UTC, demiankatz commented
@xmorave2, I don't think this is a controversial change, but I need an approval to merge -- hoping you don't mind taking a quick look. :-)

2022-05-11 06:54 UTC, xmorave2 requested changes
There are some more occurrences of `AggressiveOpts` in files **import/bin/import.bat**  and **import/bin/import.sh**

Otherwise, as you said, it is deprecated, we should not suggest to use it.

2022-05-11 13:20 UTC, demiankatz commented
Thanks, @xmorave2! I hadn't touched those scripts because I thought they were essentially vendor files coming from the SolrMarc distribution. Your comment inspired me to fix the problem upstream in SolrMarc, and I then discovered that the files do not exist there. I think they are just unused legacy scripts, so I have opened a separate PR (#2430) to remove them.  (That allows us to keep this harmless fix targeted against dev while making that slightly riskier change against dev-9.0). If you agree with this approach, please approve this PR so I can merge it. If not, I'm happy to discuss further!

2022-05-11 14:04 UTC, xmorave2 approved these changes

2022-05-11 14:06 UTC, xmorave2 commented
@demiankatz: Removing unused code is always good. I do agree with this.

2022-05-11 14:48 UTC, merged