LESS Compiler Deprecation
vufind-org/vufind pull request #2586
Opened 2022-10-14 17:50 UTC by skellamp

2022-10-14 18:09 UTC, demiankatz commented
Thanks, @skellamp!

@crhallberg, I suggested removing the active LESS compilation along with the deprecated command line LESS compiler, since both of these depend on the same underlying PHP LESS compiler, which we know does not work consistently with the Javascript-based compiler. I think getting rid of this functionality will increase our flexibility for tooling in the future theme, and I doubt that anyone is using it in production. Do you have any concerns before I merge this?

2022-10-14 18:11 UTC, demiankatz requested changes
@skellamp, I see that tests are failing here -- it looks like there are some tests that need to be removed, because the code that they cover has also been removed. If you look at the test output in the build, it should help guide you, but please let me know if you have any questions!

2022-10-17 16:50 UTC, demiankatz requested changes
Thanks again for this -- I think it's nearly done, but I found one remaining loose end to clean up.

2022-10-17 16:50 UTC, demiankatz commented on module/VuFindTheme/src/VuFindTheme/ResourceContainer.php
> -    public function addLessCss($less)
There is still one remaining reference to this method that needs to be removed from \VuFindTheme\Initializer.

2022-10-17 20:07 UTC, demiankatz approved these changes
I've run the full integration test suite, and everything is passing. I believe that this is ready to merge (and I'm happy to take care of the necessary documentation updates, once the decision to merge is made). I'm just going to wait for feedback from @crhallberg before taking those last steps.

2022-10-20 17:39 UTC, crhallberg approved these changes
I've always found the PHP LESS compiler convenient on systems that don't have Node installed, but I won't let my crutch continue to stand in the way of progress. This has been a security and deprecation concern for a while.

2022-10-21 15:42 UTC, demiankatz commented
Thanks, @skellamp and @crhallberg. All documentation is now up to date, so I am merging this!

2022-10-21 15:42 UTC, merged