Add ability to pass params into forms
vufind-org/vufind pull request #2674
Opened 2023-01-17 12:32 UTC by xmorave2

This enables to create links with urls like `/Feedback/Form/SomeForm?param=value` to prefill inputs for user, or fill hidden inputs with some dynamic value.

2023-01-17 14:29 UTC, demiankatz commented
Thanks, @xmorave2! I'm curious whether @EreMaijala has any thoughts on this, since he's more invested in the form code than I am. I also wonder whether we need to add test coverage for this new functionality, and whether we should add a configuration setting to limit which parameters may be pre-filled via URL (in case there are any possible abuses of the functionality that we might want to avoid). Any thoughts?

2023-01-18 06:15 UTC, EreMaijala requested changes
This is a good idea, but @demiankatz has valid points. We need to protect at least the read-only reserved elements (referrer, useragent, submit). Also need to ensure that this doesn't allow overriding a select field with an invalid value (I didn't test it yet), and here test coverage would help.

2023-02-22 16:02 UTC, xmorave2 commented
Thanks for review.

I added configuration for enabling prefill only for specific fields and check if some of protected fields are not prefilled.

I didn't implement prefilling for selects and checkboxes - it turned out a bit complicated and we don't even need for our use case.

2023-02-22 19:29 UTC, demiankatz requested changes
Thanks for the progress on this! I have just a few minor suggestions.

2023-02-22 19:29 UTC, demiankatz commented on config/vufind/FeedbackForms.yaml
> +#   prefillFields (array) Fields that could be prefilled by passing parametr to form URL. Could be
Typo: parametr --> parameter

2023-02-22 19:29 UTC, demiankatz commented on module/VuFind/src/VuFind/Form/Form.php
> +            $prefill = $this->sanitizePrefill($prefill);
Should we do this at the top of the function, so we only sanitize once instead of doing it on every loop iteration?

2023-02-22 19:29 UTC, demiankatz commented on module/VuFind/src/VuFind/Form/Form.php
> +        foreach ($this->getProtectedFieldNames() as $fieldName) {
You could probably eliminate this extra foreach loop by incorporating protected fields into the array_filter callback below -- e.g. change that to `return in_array($key, $prefillFields) && !in_array($key, $this->getProtectedFieldNames())`

2023-02-22 19:29 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Form/FormTest.php
> +    public function testPrefill(): void
Should put a function header on this test.

2023-02-22 19:29 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Form/FormTest.php
> +    public function testPrefillProtectedFields(): void
Also needs a function header comment.

2023-02-23 06:59 UTC, xmorave2 commented
Thanks  @demiankatz  I fixed them all.

2023-02-23 12:00 UTC, demiankatz approved these changes
Thanks, @xmorave2! I'll wait to see if @EreMaijala has any further thoughts before merging this.

2023-02-24 08:44 UTC, EreMaijala approved these changes
Looks good to me now!

2023-02-24 13:28 UTC, merged