[VUFIND-1597] include available ISSNs in OpenURLs for Serial format
vufind-org/vufind pull request #2713
Opened 2023-02-17 19:28 UTC by gmcharlt

Records whose format ends up as Serial due to vagaries of the cataloging of the original MARC record should nonetheless have any available ISSNs included in their OpenURL. With this patch, the OpenURL format is set as 'Journal' for such records.

2023-02-17 19:52 UTC, gmcharlt commented
Noting that the approach I took hews closest to the specific problem I ran into, but an alternative approach would be to simply move the test of `isset($formats[0])` to the end of the if-chain on the theory that getting any available ISSN or ISBN into the OpenURL when the format isn't precisely known to be Article, Book, or Journal will be good enough.

2023-02-17 20:13 UTC, demiankatz commented
Thanks, @gmcharlt! I've put a link to the JIRA ticket in the header here, and I've also commented with some more background/context over there. I think some more discussion may be necessary here. :-)

2023-02-20 19:12 UTC, demiankatz requested changes
Thanks, @gmcharlt, I think this is moving in the right direction, but I had one more thought...

2023-02-20 19:12 UTC, demiankatz commented on module/VuFind/src/VuFind/RecordDriver/DefaultRecord.php
> +            // monographic series.
Should we restructure this to:

```
} elseif (strlen($this->getCleanISSN()) > 0) {
    return strlen($this->getCleanISBN()) > 0 ? 'Book' : 'Journal';
....
```
...rather than having the ISBN check done independently? That way, we're more specifically adding handling for things with ISSNs, rather than very broadly capturing ISBNs. I'm concerned that we might otherwise have some unanticipated side effects for non-Book objects that happen to have ISBNs (DVDs, board games, etc.).

2023-02-21 16:56 UTC, gmcharlt commented
@demiankatz I've updated the PR with the requested change. This is on track to become a very thoroughly documented little function. :)

2023-02-21 17:31 UTC, demiankatz approved these changes
Thanks, @gmcharlt, I think this all makes a lot of sense. However, before I merge, I'm going to ask for a couple more reviews just in case somebody else thinks of something I'm overlooking!

2023-02-23 15:04 UTC, lahmann approved these changes
Thanks for the contribution @gmcharlt - I have no objections and double checked possible implications with a colleague of mine: this change will very likely improve resolver's handling of proceedings at least in our catalogues so we welcome this pull request.

2023-02-23 15:35 UTC, demiankatz commented
Thanks, @gmcharlt and @lahmann -- merging now!

2023-02-23 15:35 UTC, merged