[VUFIND-1593] Add an HTML-friendly JSON encode helper.
vufind-org/vufind pull request #2734
Opened 2023-03-01 14:38 UTC by demiankatz

TODO:
- [ ] Test everything
- [ ] Close [VUFIND-1593](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1593) when merging

2023-03-01 15:02 UTC, demiankatz commented
@EreMaijala, I have a bit more testing to do, but I'm interested in your thoughts on this approach. A few notes:

1.) I came up with a better fix for the channel escaping than #2687 -- I figured out where the double-escaping was coming from (the URL query helper in the channel provider plugin).

2.) I assume that I don't need to escape JSON differently inside inline scripts, so I just focused on JSON in HTML attributes.

3.) For consistency, a view helper seemed like the best approach... but I'm open to other ideas!

2023-03-01 16:34 UTC, demiankatz commented
At this point, all integration tests are passing, though there are some less-used templates (like WorldCatIdentities) that probably need to be manually double-checked. I'll wait to finish all the manual testing until the general approach has been approved, so I only have to do it once. :-)

2023-03-02 06:05 UTC, EreMaijala requested changes
Makes sense to me! Just a couple of tiny nitpicks in comments.

2023-03-02 06:05 UTC, EreMaijala commented on module/VuFind/src/VuFind/View/Helper/Root/HtmlSafeJsonEncode.php
> +            ? $this->getView()->plugin($outerEscaper)->__invoke($json)
Could you use the `($this->getView()->plugin($outerEscaper))($json)` style call here?

2023-03-02 06:05 UTC, EreMaijala commented on module/VuFind/src/VuFind/View/Helper/Root/HtmlSafeJsonEncode.php
> + *
This could include a short description on why this is needed.

2023-03-02 12:22 UTC, demiankatz commented
Thanks, @EreMaijala! I've incorporated your feedback, manually tested things, and added a unit test for the new helper. Hopefully this is ready to go now!

2023-03-02 12:26 UTC, EreMaijala approved these changes

2023-03-02 12:32 UTC, merged