Fix account status array for requests to match the AJAX array.
vufind-org/vufind pull request #2736
Opened 2023-03-02 11:43 UTC by EreMaijala

Now matches the logic in AbstractUserRequestAction. Fixes account status for requests getting refreshed any time e.g. holds screen loads.

2023-03-02 12:30 UTC, demiankatz requested changes
@EreMaijala, one question...

2023-03-02 12:30 UTC, demiankatz commented on module/VuFind/src/VuFind/Controller/Plugin/IlsRecords.php
> +                $accountStatus['other']++;
@EreMaijala, would it make sense to prevent this from getting out of sync by creating a `\VuFind\ILS\Logic\CountRequestsTrait` with this:

```
protected function countRequests($requests)
{
    $status = [
        'available' => 0,
        'in_transit' => 0,
        'other' => 0
    ];
    foreach ($requests as $request) {
        if (!empty($request['available'])) {
            $status['available'] ++;
        } elseif (!empty($request['in_transit'])) {
            $status['in_transit'] ++;
        } else {
            $status['other'] ++;
        }
    }
}
```

...and then refactoring this code to:

```
$callback = function ($record) {
    return $record->getExtraDetail('ils_details');
}
return $this->countRequests(array_map($callback, $records));
```

I know we talked about sharing this logic before and determined that it was not feasible... but looking at it today, I don't see why this approach wouldn't work. If you can think of a reason, I'm happy to merge this as-is, but it seemed worth reviewing again!

2023-03-02 12:46 UTC, EreMaijala commented on module/VuFind/src/VuFind/Controller/Plugin/IlsRecords.php
> +                $accountStatus['other']++;
That should work. :) I'll do that also for fines and checkouts.

2023-03-02 13:35 UTC, demiankatz commented on module/VuFind/src/VuFind/Controller/Plugin/IlsRecords.php
> +                $accountStatus['other']++;
Thanks!

2023-03-02 13:54 UTC, EreMaijala commented on module/VuFind/src/VuFind/Controller/Plugin/IlsRecords.php
> +                $accountStatus['other']++;
Okay, this spiralled into a bit larger set of changes than I expected, but now done and much better!

2023-03-02 15:00 UTC, demiankatz requested changes
Thanks, @EreMaijala. This looks good in principle, but something must be wrong. Getting some test failures:

```
There were 3 failures:



1) VuFindTest\Mink\AccountMenuTest::testIconNone

Element not found: #account-icon .account-status-none index 0

Failed asserting that false is true.



/usr/local/vufind/module/VuFind/src/VuFindTest/Integration/MinkTestCase.php:385

/usr/local/vufind/module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountMenuTest.php:320

/usr/local/vufind/module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountMenuTest.php:345

/usr/local/vufind/module/VuFind/src/VuFindTest/Feature/AutoRetryTrait.php:99



2) VuFindTest\Mink\AccountMenuTest::testIconClashes

Element not found: #account-icon .account-status-good index 0

Failed asserting that false is true.



/usr/local/vufind/module/VuFind/src/VuFindTest/Integration/MinkTestCase.php:385

/usr/local/vufind/module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountMenuTest.php:320

/usr/local/vufind/module/VuFind/tests/integration-tests/src/VuFindTest/Mink/AccountMenuTest.php:442

/usr/local/vufind/module/VuFind/src/VuFindTest/Feature/AutoRetryTrait.php:99



3) VuFindTest\Mink\SavedSearchesTest::testSaveSearch

Element not found: .createAccountLink index 0

Failed asserting that false is true.



/usr/local/vufind/module/VuFind/src/VuFindTest/Integration/MinkTestCase.php:385

/usr/local/vufind/module/VuFind/src/VuFindTest/Integration/MinkTestCase.php:472

/usr/local/vufind/module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SavedSearchesTest.php:94

/usr/local/vufind/module/VuFind/src/VuFindTest/Feature/AutoRetryTrait.php:99



FAILURES!

Tests: 2291, Assertions: 11348, Failures: 3, Skipped: 7.
```

2023-03-03 08:04 UTC, EreMaijala commented
@demiankatz Oops. I forgot to change the tests to account for the value => total change. I added the missing fields to requests while at it, though it doesnt' affect the outcome. Tests are now passing for me.

2023-03-03 13:40 UTC, demiankatz approved these changes
Thanks, @EreMaijala -- I reviewed this quite carefully, and it looks good to me! :-)

2023-03-03 13:42 UTC, merged