PSR-12: add no-break comments.
vufind-org/vufind pull request #2771
Opened 2023-03-10 20:13 UTC by demiankatz

Another PSR-12 rule that can be safely applied ahead of merging #2745 -- separating this out to make the remaining review of #2745 a little easier.

2023-03-14 19:54 UTC, demiankatz commented
@EreMaijala, I've reviewed the first two files and feel pretty confident that the missing breaks are intentional. I'm less sure about the Oauth2 file, which I think is one of yours. What do you think?

2023-03-15 06:22 UTC, EreMaijala requested changes
I find case statements flowing from one to another generally confusing and error-prone, so I'd rather get rid of them, but if you disagree, the only real issue is the UserEntity case.

2023-03-15 06:22 UTC, EreMaijala commented on module/VuFind/src/VuFind/OAuth2/Entity/UserEntity.php
> +                    // no break
This one seems like a mistake, and should actually have a break.

2023-03-15 06:22 UTC, EreMaijala commented on module/VuFind/src/VuFind/AjaxHandler/GetResolverLinks.php
> +                    // no break
I'd prefer repeating the code from the `default` case and adding a break here, but either way works for me.

2023-03-15 06:22 UTC, EreMaijala commented on module/VuFind/src/VuFind/Net/UserIpReader.php
>                          if (!empty($parts)) {
We could check for `empty($parts)` before the switch and just have return statements for `'first'` and `'last'`.

2023-03-15 07:14 UTC, EreMaijala commented
> @EreMaijala, I've reviewed the first two files and feel pretty confident that the missing breaks are intentional. I'm less sure about the Oauth2 file, which I think is one of yours. What do you think?

I believe it's a mistake, and should have a break. Functionally it doesn't change anything in any normal situation.

2023-03-15 13:39 UTC, demiankatz commented
Thanks, @EreMaijala, I agree that a little more work was helpful here. I've rewritten the first two files to avoid the need to drop through cases (and in the second file, to eliminate case entirely, as it made things much harder to understand). I also added the missing break. Two of the three files already had test coverage, so I'm confident the refactoring is okay; the third file was missing coverage, so I wrote a test and confirmed the same behavior before and after my changes.

2023-03-15 13:41 UTC, EreMaijala approved these changes

2023-03-15 13:43 UTC, merged