Fix CoverController::getImageParams isbn array check
vufind-org/vufind pull request #2800
Opened 2023-03-21 14:54 UTC by LuomaJuha

2023-03-21 16:32 UTC, demiankatz requested changes
Thanks, @LuomaJuha! I'm copying @xmorave2 into this thread in case he has any insights. I thought I had done end-to-end testing of this, but maybe I did something incorrectly or overlooked a detail. It certainly seems like you've found a gap in the code. I also have a couple of questions about implementation details (see below).

2023-03-21 16:32 UTC, demiankatz commented on module/VuFind/src/VuFind/Controller/CoverController.php
> +                $isbn = reset($isbn);
Why is this reset necessary?

2023-03-21 16:32 UTC, demiankatz commented on module/VuFind/src/VuFind/Controller/CoverController.php
> +            'isbn' => $isbn,
I think the VuFind\Cover\Loader is now expecting an 'isbns' key instead of singular 'isbn' in order to take advantage of multiple values. I wonder if `'isbns' => (array)$isbn` would be the best way to approach this.

2023-03-22 06:33 UTC, xmorave2 requested changes
Thanks @LuomaJuha for catching this! It's definitely a bug and my oversight from #2633.

2023-03-22 06:33 UTC, xmorave2 commented on module/VuFind/src/VuFind/Controller/CoverController.php
> +                $isbn = reset($isbn);
Why do you reduce the ISBNs to first one only? We probably want to pass all available ISBNs to cover loader. 
So we want something like this instead: 

```
$isbns = $params()->fromQuery($identification);
if (empty($isbns)) {
    continue;
}
if (!is_array($isbns)) {
    $isbns = [$isbns];
}
```

2023-03-22 06:33 UTC, xmorave2 commented on module/VuFind/src/VuFind/Controller/CoverController.php
> +            'isbn' => $isbn,
Yes we need `isbns` param instead of `isbn`.

2023-03-22 07:27 UTC, LuomaJuha commented on module/VuFind/src/VuFind/Controller/CoverController.php
> +                $isbn = reset($isbn);
Now it should convert them into an array as default.

2023-03-22 07:28 UTC, LuomaJuha commented on module/VuFind/src/VuFind/Controller/CoverController.php
> +            'isbn' => $isbn,
isbns it is now.

2023-03-22 07:46 UTC, xmorave2 approved these changes
Thanks for quick update @LuomaJuha. I do some hand on testing using ObalkyKnih driver with ajax covers disabled and it is working fine.

2023-03-22 09:59 UTC, demiankatz approved these changes
Looks good! Thanks, @LuomaJuha and @xmorave2!

2023-03-22 09:59 UTC, merged