Add ability to retrieve record links from ILS driver.
vufind-org/vufind pull request #2810
Opened 2023-03-29 19:22 UTC by demiankatz

TODO
- [x] Test KohaRest driver

2023-03-29 19:43 UTC, demiankatz commented
@EreMaijala, it has been an occasional request to add links directly to the Koha OPAC from VuFind, and this PR is a proof of concept to create a mechanism that allows ILS drivers to provide links to record drivers. I'm interested in your thoughts. In particular:

1.) Can you test the KohaRest changes? I wrote the code but can't easily test it.

2.) Do you think it's sufficient to have a view_in_opac translation string that we can override, or should we make the description configurable via KohaRest.ini?

3.) Any other thoughts on the general architecture here?

Since this adds a new language string, I'm targeting it for the 9.1 release.

2023-04-04 17:42 UTC, EreMaijala requested changes

2023-04-04 17:42 UTC, EreMaijala commented on config/vufind/KohaRest.ini
> +;opacURL = "http://koha-server/cgi-bin/koha/opac-detail.pl"
This works right now, but I'd like the configuration to specify a complete URL with a placeholder for the ID so that the URL can be formulated freely. Something like `opacURL = "http://koha-server/cgi-bin/koha/opac-detail.pl?biblionumber=%%id%%"` would be great.

2023-04-04 18:35 UTC, demiankatz commented on config/vufind/KohaRest.ini
> +;opacURL = "http://koha-server/cgi-bin/koha/opac-detail.pl"
Thanks, I've added the suggested flexibility, as well as the beginning of a unit test for the KohaRest driver (currently covering only the newly-added method).

2023-04-11 16:34 UTC, EreMaijala approved these changes

2023-04-11 16:51 UTC, merged