Fix and clean up results scripts.
vufind-org/vufind pull request #2878
Opened 2023-05-11 07:15 UTC by EreMaijala

- This consolidates initialization of scripts for search results to VuFind.initResultScripts function and adds initializations that were missing from the previous implementation in combined-search.
- results-scripts.phtml is now used for loading all results-related scripts.
- Some additional checks are added to ensure re-triggering initialization doesn't load e.g. covers again.

Extracted from PR #2804

TODO
- [ ] Update changelog when merging

2023-05-11 07:18 UTC, EreMaijala commented
I've tested the changes and run Mink tests and everything seems to work properly.

2023-05-11 20:08 UTC, demiankatz requested changes
Thanks, @EreMaijala -- didn't have time for an exhaustive test yet, but I did spot one thing that I wanted to ask about...

2023-05-11 20:08 UTC, demiankatz commented on themes/bootstrap3/templates/search/results.phtml
> -  $this->resultsClass = 'search-results-' . strtolower($searchClass);
Why are you removing resultsClass here? I think this value is still used in subtemplates like list-list.phtml and list-grid.phtml. Am I missing something?

2023-05-12 04:51 UTC, EreMaijala commented on themes/bootstrap3/templates/search/results.phtml
> -  $this->resultsClass = 'search-results-' . strtolower($searchClass);
Oops, thanks for spotting that. It was a bad pick from #2804.

2023-05-12 16:15 UTC, demiankatz requested changes
@EreMaijala, it looks like merging #2876 has introduced some conflicts here. Can you take a look?

2023-05-12 16:50 UTC, EreMaijala commented
@demiankatz Resolved!

2023-05-12 16:57 UTC, demiankatz requested changes
One small deprecation-related comment.

Beyond that, this kind of feels to me like a 10.0 change, because of the change in the behavior of the results-scripts.phtml (which is a file likely to be locally overridden), significant refactoring of Javascript, etc. Would you agree? Is this perhaps the one that prompts us to start dev-10.0, so that we can then pile the AJAX results on top?

2023-05-12 16:57 UTC, demiankatz commented on themes/bootstrap3/js/common.js
> +    container.find('a.qrcodeLink').click(function qrcodeToggle() {
Should this be `.on("click", ...`?

2023-05-12 16:59 UTC, EreMaijala commented on themes/bootstrap3/js/common.js
> +    container.find('a.qrcodeLink').click(function qrcodeToggle() {
Yes, fixed.

2023-05-12 16:59 UTC, EreMaijala commented
@demiankatz I agree, dev-10.0 would be in order.

2023-05-25 14:01 UTC, demiankatz approved these changes
This looks good to me, and all tests are passing. I plan to merge it next week after the `dev-10.0` branch is established.

I propose this text for the changelog:

`- Javascript initialization has been revised and refactored for reduced redundancy and greater flexibility. Significant changes that could impact backward compatibility include refactoring additional logic from search/results.phtml into search/results-scripts.phtml and moving the initResultScripts Javascript function from combined-search.js into common.js. See [[https://github.com/vufind-org/vufind/pull/2878|pull request #2878]] for details.`

2023-05-31 14:57 UTC, merged