Upgrade php-cs-fixer to v3.17.0.
vufind-org/vufind pull request #2907
Opened 2023-05-25 21:30 UTC by demiankatz

I had to disable the `statement_indentation` rule for templates to avoid lots of problems, but at least some of these other changes do result in cleaner code.

TODO
- [ ] Run full test suite.

2023-05-25 21:48 UTC, demiankatz commented
All tests are passing, though I plan to do another review of my changes next week with a fresher brain, just to be on the safe side. :-)

2023-05-26 06:04 UTC, EreMaijala requested changes
I agree that the results are good. I had just a couple of minor issues with indented comments.

2023-05-26 06:04 UTC, EreMaijala commented on module/VuFind/src/VuFind/ILS/Driver/Virtua.php
> +            // Chrono
I think it would be cleaner to move these inside the next `else` block.

2023-05-26 06:04 UTC, EreMaijala commented on module/VuFind/src/VuFind/RecordDriver/SolrOverdrive.php
> +                // If we aren't locked in, we can show all formats
I think it would be cleaner to rephrase this so that it can be moved into the next `else` block, like `// Not locked in, show all formats`.

2023-05-26 11:52 UTC, demiankatz commented
Thanks, @EreMaijala, I've made the requested adjustments! I wish they'd make up their mind about comment indentation, because I feel this has switched back and forth a few times, but your suggestions will make this more predictable in future even if it changes again. :-)

2023-05-26 11:56 UTC, demiankatz commented
Hmm, that's weird. I edited both files through the web-based editor here since the changes were trivial... but that somehow messed up the indentation of the else clauses. Fixed now. Not sure exactly what I did to introduce that indentation problem!

2023-05-26 12:02 UTC, EreMaijala approved these changes

2023-05-26 12:06 UTC, EreMaijala commented
@demiankatz Odd, but now it seems to be all good.

2023-05-28 18:06 UTC, merged