Fix page param out of range at search results
vufind-org/vufind pull request #2940
Opened 2023-06-12 10:30 UTC by xmorave2

To reproduce:
1. Enable ability to change number of result per page
2. Make e search
3. Go to last page
4. Change the results per page to higher option
5. Without the fix, you should see empty results. With this patch, you'll be redirected to last available page

Or just change the page param in url manually ;)

I am not really sure if this is the right place where to make a fix, so suggestion are more than welcome ;)

2023-06-12 12:32 UTC, demiankatz commented
Thanks, @xmorave2, this seems to me like a reasonable place for the logic. I'd also be interested to hear what @EreMaijala thinks, though, in case I'm overlooking anything.

2023-06-12 12:44 UTC, EreMaijala commented on module/VuFind/src/VuFind/Controller/AbstractSearch.php
> +            $this->redirect()->toRoute('search-results', [], [ 'query' => $queryParams ]);
Should this be returned to avoid further processing?

2023-06-13 07:34 UTC, xmorave2 commented on module/VuFind/src/VuFind/Controller/AbstractSearch.php
> +            $this->redirect()->toRoute('search-results', [], [ 'query' => $queryParams ]);
Definitely, thanks @EreMaijala, I fixed it.

2023-06-13 08:44 UTC, EreMaijala approved these changes
Looks good to me now!

2023-06-13 13:54 UTC, demiankatz commented
I just tried running the full test suite and am getting failures, but it may be due to a configuration error on my end. I'm out of time for today but will try to give this another look tomorrow!

2023-06-13 16:41 UTC, EreMaijala requested changes, later dismissed
Right, there's an issue when there are no results. `$lastPage` becomes 0 and causes and endless redirect.

2023-06-13 18:33 UTC, demiankatz requested changes
Thanks for figuring this out, @EreMaijala. Can you fix this edge case when time permits, @xmorave2? Maybe it would also be useful to add a Mink test to capture the "access past end of list" behavior to catch future regressions.

2023-06-19 15:06 UTC, demiankatz approved these changes
Thanks, @xmorave2 -- all tests are passing now, and I added a small test to cover this edge case.

2023-06-19 15:11 UTC, merged

2023-06-20 05:55 UTC, xmorave2 commented
Thanks @demiankatz