Add support for advanced search with Blender.
vufind-org/vufind pull request #3068
Opened 2023-09-04 10:18 UTC by EreMaijala

This PR adds support for advanced search with Blender. It also adds a proper controller for Blender for the different actions and so that Blender can be used as the default module as desired. The old Search/Blended route is still supported for back-compatibility.

2023-09-05 12:34 UTC, demiankatz requested changes
@EreMaijala, I haven't had time for a hands-on test yet, but here are a few initial comments.

2023-09-05 12:34 UTC, demiankatz commented on config/vufind/Blender.ini
> +; searches (Solr, SolrAuth, EDS and Primo do).
Maybe we should recommend an action here if they DON'T support advanced searches. Something like "You can comment out or delete all of the options in this section to disable advanced search in situations where all backends cannot support it."

2023-09-05 12:34 UTC, demiankatz commented on module/VuFind/src/VuFind/Controller/BlenderController.php
> +            && $config->Record->next_prev_navigation;
This could be `$config->Record->next_prev_navigation ?? false` -- I imagine this was copy-pasted from elsewhere, but probably doesn't hurt to optimize it.

2023-09-05 12:34 UTC, demiankatz commented on module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
> +                    $this->assertNull(null);
Is this to satisfy tests that would otherwise complain that they have no assertions? If so, maybe adding a comment here to explain that will prevent future confusion.

2023-09-06 07:00 UTC, EreMaijala commented on config/vufind/Blender.ini
> +; searches (Solr, SolrAuth, EDS and Primo do).
Good idea, and thanks for the suggestion. Now added.

2023-09-06 07:00 UTC, EreMaijala commented on module/VuFind/src/VuFind/Controller/BlenderController.php
> +            && $config->Record->next_prev_navigation;
Fixed.

2023-09-06 07:01 UTC, EreMaijala commented on module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
> +                    $this->assertNull(null);
Yes, and it also makes the check count in test statistics. Comment added.

2023-09-06 18:02 UTC, demiankatz approved these changes
Looks good and works for me. I wish there was a better way to manage the help translations since so much of the text is redundant, but I don't have any brilliant ideas there.

2023-09-06 18:05 UTC, merged

2023-09-06 18:07 UTC, EreMaijala commented
@demiankatz I agree that there's a lot of redundant text, but I think it still makes sense from the point of customization. It's easier to update complete pages e.g. if you want to give your audience specific hints or search examples, and you can be sure that they don't affect other pages.