Put single quotes around language strings containing double quotes.
vufind-org/vufind pull request #3089
Opened 2023-09-13 18:56 UTC by demiankatz

This PR implements a change suggested in #3048 to improve Lokalise compatibility. I think this change is probably worth making whether or not it impacts Lokalise, though, since it gets our .ini files closer to validity in terms of generic .ini standards. I also caught and fixed quite a few quote-related problems in various files as a result of running this new normalization.

TODO
- [ ] Test that this makes a difference in Lokalise before merging

2023-09-18 19:44 UTC, demiankatz commented
@EreMaijala, as discussed on Slack, I've added escaping of quotes inside the same type of quote, to make this create fully standards-compliant .ini files. I don't have time to run the full test suite today, but if this looks good to you, I can do so tomorrow.

2023-09-19 11:03 UTC, demiankatz commented
Full test suite is passing.

2023-09-19 11:15 UTC, EreMaijala requested changes

2023-09-19 11:15 UTC, EreMaijala commented on languages/ca.ini
> +verification_email_notification = "S'ha fet una sol·licitud per verificar la vostra adreça de correu electrònic del vostre compte amb %%library%%."
Shouldn't this one be changed to single quotes as well?

2023-09-19 11:22 UTC, EreMaijala commented on languages/ca.ini
> +verification_email_notification = "S'ha fet una sol·licitud per verificar la vostra adreça de correu electrònic del vostre compte amb %%library%%."
No, I was mistaken, all good!

2023-09-19 11:22 UTC, EreMaijala approved these changes

2023-09-19 11:23 UTC, merged