Narrow the first holdings tab column to 25% width
vufind-org/vufind pull request #3096
Opened 2023-09-15 21:08 UTC by maccabeelevine

Based on [discussion ](https://github.com/vufind-org/vufind/pull/3094#pullrequestreview-1629115325)with @crhallberg for #3094.  Tables in the holdings tab are only 50/50 as a default from bootstrap; there was likely no specific decision for these tables.  The first column tends to be pretty short, while the second may be more variable.  In #3094 we are adding a whole lot of content to the second column that would benefit from some extra space.  25/75 may be reasonable.

Auto-layout without explicit width percentages would solve the same problem but make each table look different and scattered.  I prefer the fixed layout and I think @crhallberg agreed in discussion earlier today.

2023-09-15 21:09 UTC, maccabeelevine commented on themes/bootstrap3/less/components/record.less
> +.holdings-tab table {
I know you suggested a class name on the table itself, but I think this does the trick?  If there are counter-examples of tables on the holdings tab that should be treated differently, then I can narrow it down.

2023-09-22 10:39 UTC, demiankatz reviewed
I just took a look at this, and I wonder if we'd be better off setting min-width/max-width instead of a fixed 25% width, to give it just a little more "wiggle room." When I tested with the Demo driver, I ended up with this scenario:

Before (dev branch):
![image](https://github.com/vufind-org/vufind/assets/309069/c7682aea-5387-4ca6-ad7c-1abbd8d0c5c3)

After (this PR):
![image](https://github.com/vufind-org/vufind/assets/309069/77a31f2a-9e8b-4def-85c9-5c91d4193f60)

I think that looks worse after the change, though I realize that the copy data provided by the Demo driver is not very realistic, so this exact scenario is pretty unlikely in real life. Still, it feels like setting a min and a max might accommodate a broader range of scenarios without interfering with your primary intent of making the left column take up less than half the screen when it doesn't need all that space.

Also, have you tested this on mobile? I wonder if 25% is too narrow on a very tiny display, and maybe a pixel max would be better than a percentage max.

Obviously, I defer to whatever @crhallberg thinks... but just trying to get the ball rolling. :-)

2023-10-18 15:44 UTC, crhallberg commented on themes/bootstrap3/less/components/record.less
> +.holdings-tab table {
I have no counter examples, just thought it would be better for customization.

2023-10-18 15:45 UTC, crhallberg commented
The reason we need a fixed width (for now) is we want things to line up from table to table. If we give them flexibility, they won't line up if your example sits next to one whose label is just "Online" and doesn't expand. Is this a huge issue? No. But that's the consideration.

2023-10-19 10:58 UTC, demiankatz commented
@crhallberg, do you think it's worth mocking up an example of your counter-argument, so we can decide which approach looks better? I think I _might_ prefer inconsistent table sizes across holdings locations over unnecessarily wrapped/crushed-looking text. But maybe I wouldn't if I actually saw it.

2023-10-19 11:00 UTC, demiankatz commented on themes/bootstrap3/less/components/record.less
> +.holdings-tab table {
Actually, I think we do need to use a more specific class, because otherwise the "Most Recent Received Issues" table will get crushed: https://github.com/vufind-org/vufind/blob/dev/themes/bootstrap3/templates/RecordTab/holdingsils.phtml#L154

Now whether it makes any sense for this to be a single-column table instead of some other HTML structure is a separate question. But it is at present, so we should avoid breaking it.

2023-11-14 15:29 UTC, crhallberg commented
Behold! The horror!

![image](https://github.com/vufind-org/vufind/assets/451107/479f9493-139f-4d4d-8075-9906c6b7459c)

In all honesty, I thought this would be worse. And it might be if there are multiple campuses with one location each. I also had to set `white-space: nowrap` to force the issue I was expecting. Removing `table-layout: fixed` gave the right column more room with very readable left columns. `width: fit-content` had no effect, since the text wrapped.

2023-11-14 15:33 UTC, crhallberg requested changes

2023-11-14 15:33 UTC, crhallberg commented on themes/bootstrap3/less/components/record.less
> +  }
In response to the discussion on the main page, I think we can remove this part and let the table auto layout. We can do a min-width if we're worried about collapse of like 20%.

2023-11-14 17:10 UTC, demiankatz requested changes
@maccabeelevine, what do you think? Can you resolve conflicts here and adjust width as discussed (unless you prefer a different approach)?

2023-11-21 14:06 UTC, maccabeelevine commented
> @maccabeelevine, what do you think? Can you resolve conflicts here and adjust width as discussed (unless you prefer a different approach)?

I agree that auto-width surprisingly seems to work fine, as long as it's limited to that particular table.  I don't think we need a min-width (but can add that if folks disagree).  I think this is good now.

2023-11-21 22:13 UTC, demiankatz approved these changes
Thanks, @maccabeelevine, looks good to me! I'll wait to merge this until @crhallberg also gives it a passing review.

2023-11-27 19:30 UTC, crhallberg commented
Do we want to put a minimum width on these columns? You can't use a percent but I was able to approximate a percentage by using `min-width: 10vw` on `td`.

2023-11-27 20:16 UTC, maccabeelevine commented
> Do we want to put a minimum width on these columns? You can't use a percent but I was able to approximate a percentage by using `min-width: 10vw` on `td`.

@crhallberg Yes I think that's a good idea to prevent the worst effects of making it dynamic.  I made the change to both th and td cells.

2023-11-27 21:51 UTC, crhallberg approved these changes

2023-11-28 12:55 UTC, merged

2023-11-28 12:55 UTC, demiankatz commented
Thanks, @crhallberg and @maccabeelevine.

2023-11-28 12:55 UTC, demiankatz commented
In retrospect, I should have changed the commit message when merging this since it has evolved a bit since it started. Alas, didn't think of that soon enough.

2023-11-28 13:15 UTC, maccabeelevine commented
> In retrospect, I should have changed the commit message when merging this since it has evolved a bit since it started. Alas, didn't think of that soon enough.

That's my bad.  But in some random chaotic version of the data it will be exactly 25% width! :)