Upgrade to Solr 9.3.0.
vufind-org/vufind pull request #3132
Opened 2023-09-29 14:31 UTC by demiankatz

This PR upgrades to the latest Solr release and removes the deprecated enableRemoteStreaming setting (which is now controlled by an environment variable instead of the config file). While our existing enableRemoteStreaming settings were inconsistent with one another, I do not believe that there was any good reason to have it enabled under any circumstances, so removing it should not cause a problem.

TODO
- [ ] Rebuild browse handlers
- [ ] Test everything

2023-10-02 10:28 UTC, EreMaijala commented
@demiankatz As far as I can see this could well be included in VuFind 9.1.

2023-10-02 13:52 UTC, demiankatz commented
Thanks, @EreMaijala, let's discuss on tomorrow's Community Call!

2023-10-03 13:08 UTC, EreMaijala requested changes

2023-10-03 13:08 UTC, EreMaijala commented on solr/vufind/authority/conf/solrconfig.xml
> +  <luceneMatchVersion>9.3.0</luceneMatchVersion>
I don't think this is correct. Solr 9.3.0 ships with Lucene 9.7.0, so we should bump this to `9.7`. Solr's examples don't include the third part, so I'd follow that convention.

2023-10-03 14:08 UTC, demiankatz commented on solr/vufind/authority/conf/solrconfig.xml
> +  <luceneMatchVersion>9.3.0</luceneMatchVersion>
I've fixed this and also re-run the full test suite to confirm that nothing has broken.

2023-10-03 18:04 UTC, EreMaijala approved these changes

2023-10-03 18:14 UTC, merged