Display the pickup location of waiting Koha reserves
vufind-org/vufind pull request #3311
Opened 2024-01-15 00:11 UTC by alexklbuckley

It would be nice if the VuFind search result and record pages should show the location that waiting Koha reserves are currently sitting at awaiting pickup, wording like  'On Reserves Shelf at X' would be helpful for library users.

2024-01-15 11:31 UTC, demiankatz requested changes
Thanks, @alexklbuckley!

Regarding unit tests, you can find the KohaRest driver's test class here: https://github.com/vufind-org/vufind/blob/dev/module/VuFind/tests/unit-tests/src/VuFindTest/ILS/Driver/KohaRestTest.php

Regarding the overall approach, I think unfortunately that we may need to add some new functionality in order to make this work right with i18n. As currently designed, the 'status' value returned by the ILS driver gets run through VuFind's transEsc() function to translate it to the user's selected language. However, since the string used here has a dynamic component, that's not really going to be practical. I'm wondering if we should add a new optional key to the ILS driver return value called statusPlaceholderValues (or something like that) so that we can use a more generic key -- then we could just set $status to something like 'on_reserves_shelf_at' and the language files could map `on_reserves_shelf_at = "On Reserves Shelf at %%location%%"` and we could set statusPlaceholderValues to an array that maps `['%%location%%' => $waitingAtLocation]`. Implementing this would require us to trace all the places where 'status' is currently translated (there are several) and add the placeholder array when it exists.

What do you think? I'm happy to help with some of the implementation (and pointing out all the places where the work would need to be done), if you think this would be a productive path forward.

I'd be interested in hearing @EreMaijala's thoughts on all this too, as he's done most of the recent KohaRest driver development.

2024-01-15 11:43 UTC, EreMaijala requested changes
I'm not sure I understand the use case for this. Since the location is already displayed for each item, what benefit is there for displaying it in the status as well?

2024-01-18 06:05 UTC, alexklbuckley commented
Hi @demiankatz and @EreMaijala , 

Thanks so much both for your responses. Just to let you know, I am seeking feedback from our partner library as to why they think having the location in the status would be helpful. 

I'll pass this information on ASAP once I hear back :)

Thanks,
Alex

2024-01-21 21:54 UTC, alexklbuckley commented
Hi @demiankatz and @EreMaijala  , 

I have heard back from our partner library.  They have reflected and concluded as the out-of-the-box behaviour shows the location of each item,  they are happy to keep the out-of-the-box behaviour.

That being the case I am going to close this pull request.

Thank you very much both for your time!

Thanks
Alex

2024-01-21 21:54 UTC, closed without merging