Show a Recalled message for recalled items, and show recalls alongside holds
vufind-org/vufind pull request #3410
Opened 2024-02-14 03:27 UTC by aleishaa

NOTE: This depends on Bug 36075 to be pushed to Koha

https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36075

2024-02-14 11:38 UTC, demiankatz requested changes
@aleishaa, thanks for sharing this! Would it be possible to set this up so that it doesn't fail if the recalls endpoint does not exist? It's possible that people will upgrade VuFind before upgrading their Koha instance or REST plugin, and we don't want that scenario to cause fatal errors for people. We could either add a config setting to toggle the recall retrieval, or we could put a try..catch around the recall lookup... or maybe both, in that we could create a setting to "tolerate recall failures" or something like that. What do you think?

Also interested in @EreMaijala's opinion.

2024-02-14 12:11 UTC, EreMaijala commented
Perhaps a setting to enable recalls? Something like this in KohaRest.ini:
```
[Holds]
; Uncomment the following like to enable recalls (disabled by default). Requires a 
; Koha version that includes 
; https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36075
;enableRecalls = true

```
This would also ensure that recalls are not checked if the library doesn't use them.

2024-02-14 12:16 UTC, EreMaijala commented on module/VuFind/src/VuFind/ILS/Driver/KohaRest.php
> +        'recalled' => 'Item requested - due date changed - return on due date',
This should be a translation code like `ILSMessages::renewal_recalled`. We are now adding ILS message translations to ILSMessages text domain, so the actual text would be in e.g. `languages/ILSMessages/en.ini`.

2024-02-14 16:24 UTC, demiankatz commented
@aleishaa, I also noticed that this PR had a conflict with dev, so I went ahead and resolved it for you. I noticed while doing so that you seem to be using your local dev branch as the basis of this PR. I'd recommend creating a different named branch for each PR you commit, since changing a branch will also cause updates to the associated PR, and it's easy to accidentally send the wrong changes to the wrong PR if you use your dev branch as the basis. I don't think it will cause a problem here as long as we're all careful, but I'd recommend doing things differently for your next PR, if possible. :-)

2024-02-15 20:45 UTC, aleishaa commented
thank you both for the notes! i'll close the pull request and do some better branches and work in your suggestions :)

2024-02-15 20:45 UTC, closed without merging

2024-02-16 01:55 UTC, aleishaa commented
I've created two new pull requests for the work referenced here:

- https://github.com/vufind-org/vufind/pull/3421
- https://github.com/vufind-org/vufind/pull/3422

Thanks for your suggestions!