Clean up unused code and variables.
vufind-org/vufind pull request #3456
Opened 2024-02-28 16:49 UTC by demiankatz

This PR cleans up some unused code identified by Psalm. It is not comprehensive -- there are still more unused code warnings that need to be addressed -- but it makes significant progress in resolving known issues.

2024-02-28 16:51 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/EDSTest.php
> +     * @return EDS
This incorrect annotation was causing many false-positive warnings in Psalm.

2024-02-28 16:52 UTC, demiankatz commented on module/VuFindTheme/src/VuFindTheme/Initializer.php
> -        $lessActive = false;
This code was orphaned when PHP LESS compilation was removed in release 9.0 -- see #2586.

2024-03-05 18:47 UTC, EreMaijala requested changes
Just a couple of nits..

2024-03-05 18:47 UTC, EreMaijala commented on module/VuFind/src/VuFind/RecordDriver/Feature/MarcAdvancedTrait.php
> +                            ? ($this->subjectSources[$sourceIndicator] ?? '')
I think this null coalesce is unnecessary since isset won't be true for null.

2024-03-05 18:47 UTC, EreMaijala commented on module/VuFind/src/VuFind/RecordDriver/Feature/MarcAdvancedTrait.php
> +                        $source = (isset($this->subjectSources[$sourceIndicator]))
Unnecessary enclosing parenthesis

2024-03-05 18:53 UTC, demiankatz commented
Thanks, @EreMaijala! That's a good catch; I'm pretty sure the code you highlighted simplifies all the way down to:

```
                        $source = $this->subjectSources[$sourceIndicator]
                            ?? $this->getSubfield($result, '2');
```

2024-03-05 19:06 UTC, EreMaijala approved these changes
Looks good to me now!

2024-03-05 19:06 UTC, merged