Introduce UserService to centralize logic.
vufind-org/vufind pull request #3485
Opened 2024-03-07 13:50 UTC by demiankatz

This PR begins to introduce the Db\Service infrastructure that will be a key component of our eventual Doctrine migration (see #2233). As of this PR, only one service (UserService) is introduced, and it is currently used for the sole purpose of centralizing encryption logic related to catalog passwords. Some of the classes and infrastructure introduced here may seem excessive or pointless at this stage, but they will serve a greater purpose as the code evolves further.

TODO
- [ ] Fix broken tests

2024-03-08 18:05 UTC, EreMaijala requested changes
I think this is a good start. 

How would you feel about prefixing "service" with "db" in most places? Like
AbstractDbService
DbServiceAwareTrait
DbServiceAwareInterface
protected $dbServiceManager;

I think that would alleviate some potential confusion and possible clashes with any other services.

2024-03-08 18:05 UTC, EreMaijala commented on module/VuFind/src/VuFind/Db/Service/UserService.php
> +    public function encryptOrDecrypt($text, $encrypt = true)
Could we expose something like `encryptData` and `decryptData` and make this protected? That would make the intent of the method calls immediately obvious.

2024-03-08 18:21 UTC, demiankatz commented
@EreMaijala, your suggestions all make sense to me. It will take a little time to apply them first to the doctrine branch and then backport them to here, but I think it's worth the effort. I'll request a new review once I've had time to work through it all.

2024-03-11 17:46 UTC, demiankatz commented
Thanks again, @EreMaijala -- I've made your suggested changes here and in #2233.

2024-03-12 15:29 UTC, EreMaijala approved these changes

2024-03-12 17:23 UTC, merged