Add an option to run psql without sudo.
vufind-org/vufind pull request #3508
Opened 2024-03-13 19:00 UTC by EreMaijala

At least on macOS psql installed with homebrew needs to be run without sudo, and macOS doesn't support `su -c`either, so this adds an option to disable them.

2024-03-13 19:04 UTC, demiankatz requested changes
Would this be easier to read and maintain if we added a new "execute_psql" task that takes the SQL to execute as an argument, and we put the conditional logic in there?

If you don't think it's worth the time to refactor, I can merge this as-is, but that seemed like a potentially significant improvement, so I thought I'd ask first. :-)

2024-03-13 19:15 UTC, EreMaijala commented
@demiankatz Thanks for asking, but I'd rather keep it like it is because handling the quotes would get more complicated and the phing output would look terrible.

2024-03-13 19:29 UTC, demiankatz approved these changes
Good points, @EreMaijala. I guess there are limits to how much refactoring you can do in a Phing configuration. ;-)

2024-03-13 19:29 UTC, merged

2024-03-14 07:08 UTC, EreMaijala commented
@demiankatz Indeed. It'd be nice to have subtasks or utility tasks..