VUFIND-1680 / phpCas 1.6 update
vufind-org/vufind pull request #3550
Opened 2024-04-02 14:23 UTC by mathieugrimault

Add phpCas/service_base_url parameter
Change phpCas logging

see : https://openlibraryfoundation.atlassian.net/browse/VUFIND-1680

2024-04-02 18:04 UTC, demiankatz requested changes
Thanks, @mathieugrimault! See below for a few suggestions. Also note that there's a small style issue you can automatically fix by running `composer fix` and committing the resulting changes.

2024-04-02 18:04 UTC, demiankatz commented on module/VuFind/src/VuFind/Auth/CAS.php
> +            if (isset($cas->debug) && ($cas->debug)) {
This could be simplifed to `if ($cas->debug ?? false) {`

2024-04-02 18:04 UTC, demiankatz commented on module/VuFind/src/VuFind/Auth/CAS.php
> +            $service_base_url = null;
As a minor point of style, I'd rename this variable to `$serviceBaseUrl` since we generally use camelCase instead of snake_case for PHP variables.

2024-04-02 18:04 UTC, demiankatz commented on module/VuFind/src/VuFind/Auth/CAS.php
> +                    parse_url($this->getConfig()->Site->url, PHP_URL_SCHEME) . '://' .
Is it worth calling parse_url just once and then processing the array it returns? Seems like that might be more efficient. Also, do we need to assemble this a little more carefully (e.g. checking whether some components are missing)? In particular, if there is a port number, do we need to add a ':' in front of it? I think parse_url just returns an integer in that situation.

2024-04-02 18:04 UTC, demiankatz commented on module/VuFind/src/VuFind/Auth/CAS.php
> +                    parse_url($this->getConfig()->Site->url, PHP_URL_SCHEME) . '://' .
Another possibility might be to use a regular expression to extract the beginning of the URL, if that's easier than messing with parse_url.

2024-04-03 07:43 UTC, mathieugrimault commented
> Thanks, @mathieugrimault! See below for a few suggestions. Also note that there's a small style issue you can automatically fix by running `composer fix` and committing the resulting changes.

I suppose `composer fix` is `vendor/bin/php-cs-fixer fix module/VuFind/src/VuFind/Auth/` ? It does nothing :/

2024-04-03 14:57 UTC, demiankatz requested changes
Thanks again for the work on this, @mathieugrimault! Since I can't test this for real, I decided to write some unit tests to cover various scenarios in configuration processing. This revealed a few minor bugs. I have refactored the code to make testing easier, and I have fixed the bugs (mainly related to missing elements in the parse_url return array) in the refactored code.

Can you please test this revised version and make sure it works correctly in your real-world scenario? Once you confirm that it is working (and if you approve of my changes), please let me know and I can merge the PR.

2024-04-03 15:38 UTC, mathieugrimault commented
Thanks Demain !
All tests are OK, you can merge.

2024-04-03 15:53 UTC, demiankatz approved these changes
Thanks again, @mathieugrimault -- merging now!

2024-04-03 15:54 UTC, merged