Refactor AuthManager to use UserService instead of table object
vufind-org/vufind pull request #3636
Opened 2024-05-02 13:19 UTC by demiankatz

This PR refactors the AuthManager to use the new UserService instead of depending on the legacy Laminas table gateway. It also creates a new interface to encapsulate session persistence of user data. Right now, the UserService implements both the session and database interfaces, but these could theoretically be split apart in future.

2024-05-02 15:18 UTC, EreMaijala requested changes

2024-05-02 15:18 UTC, EreMaijala commented on module/VuFind/src/VuFind/Auth/Manager.php
> +        protected UserServiceInterface&UserSessionPersistenceInterface $userService,
Even though it's currently the same service implementing both interfaces, I think it would make any future refactoring easier if we had them as separate constructor parameters / member variables.

2024-05-02 15:18 UTC, EreMaijala commented on module/VuFind/src/VuFind/Auth/UserSessionPersistenceInterface.php
> +    public function createEntity(): UserEntityInterface;
Is this in the interface for upcoming needs? And why in both interfaces?

2024-05-02 15:18 UTC, EreMaijala commented on module/VuFind/src/VuFind/Db/Row/User.php
> +        return DateTime::createFromFormat('Y-m-d H:i:s', $this->last_login, new \DateTimeZone('UTC'));
I can't see the time zone setting make any difference since the timestamp doesn't include a time zone in the database. Is there a reason for it? If so, a comment would be nice. :)

2024-05-02 16:37 UTC, demiankatz commented on module/VuFind/src/VuFind/Auth/UserSessionPersistenceInterface.php
> +    public function createEntity(): UserEntityInterface;
Copy and paste error. :-)

2024-05-02 16:38 UTC, demiankatz commented on module/VuFind/src/VuFind/Db/Row/User.php
> +        return DateTime::createFromFormat('Y-m-d H:i:s', $this->last_login, new \DateTimeZone('UTC'));
Copied and pasted from elsewhere; I'll remove it. :-)

2024-05-02 16:48 UTC, demiankatz commented on module/VuFind/src/VuFind/Auth/Manager.php
> +        protected UserServiceInterface&UserSessionPersistenceInterface $userService,
Done!

2024-05-02 18:12 UTC, demiankatz commented
Thanks, @EreMaijala -- the issues you highlighted should be fixed now, and the test suite is still passing.

2024-05-03 05:28 UTC, EreMaijala approved these changes

2024-05-03 12:04 UTC, merged