gh-pages: Update Jekyll
vufind-org/vufind pull request #3671
Opened 2024-05-16 19:13 UTC by crhallberg

Jekyll was out of date enough to make standing up a dev instance difficult. These updates help enormously.

2024-05-16 19:14 UTC, crhallberg commented
I see now that 025c5a3, 425e994, fa69623 are accessibility fixes. I can cherry-pick those to another branch, since I have more accessibility changes coming for the wiki.

DONE.

2024-05-16 19:50 UTC, demiankatz requested changes
Thanks, @crhallberg, if you don't mind cherry-picking those accessibility fixes to a separate PR, that seems like a good idea -- then if we have trouble getting these major updates to deploy correctly, we can roll them back without losing the other changes.

See below for a question about the deployment process.

Is there somewhere we can see the updated version of the webpage before we commit to deploying it? Is there a way to confirm that the updated version has successfully deployed after this gets merged?

2024-05-16 19:50 UTC, demiankatz commented on .github/workflows/jekyll.yml
> +    branches: ["update-v231"]
Should this be gh-pages for when we merge this?

2024-05-22 15:41 UTC, demiankatz approved these changes
Okay, here goes something....

2024-05-22 15:42 UTC, merged