Add sort option to AbstractSearchObject recommendations.
vufind-org/vufind pull request #3673
Opened 2024-05-17 11:41 UTC by demiankatz

I thought it might be useful to add the ability to sort search-based recommendations -- e.g. to display "new items" with a `first_indexed desc` sort. I also simplified the comments in searches.ini by making all of the AbstractSearchObject subclasses refer back to CatalogResults for parameter definitions, to reduce the amount of duplicate documentation.

2024-05-17 11:42 UTC, demiankatz commented
While working on this, I also thought it might be useful to build a trait for parsing configurations which could add named argument support similar to PHP's... that would make some configurations easier and more readable. But that's a project for another day!

2024-05-21 13:17 UTC, maccabeelevine requested changes
I like adding the sort option where it works, and I like the documentation simplification in theory, but I'm not sure if it may add some confusion about the details.

2024-05-21 13:17 UTC, maccabeelevine commented on config/vufind/searches.ini
> +;       for parameter definitions. Note that some may not apply to this search backend.
I like the idea of slimming down the descriptions, but I think we should be clear about which backends support which options, especially with the EBSCO ones where it is so confusing to begin with.  We could still say "See CatalogResults above for parameter definitions" but then say "XYZ are not supported on this backend" or something like that.  I.e. for sort, it is definitely not supported (yet anyway) for the LibGuides recommendations.

And for the [filter ini section] behavior, I didn't design it with EDS and EPF in mind, and so I didn't say in searches.ini that they supported it, but I'm not actually sure either way.

2024-05-21 13:17 UTC, maccabeelevine commented on module/VuFind/src/VuFind/Recommend/AbstractSearchObject.php
> +                $params->setSort($this->sort, true);
What's the intent behind the second param ($force) = true?

2024-05-21 19:06 UTC, demiankatz commented on module/VuFind/src/VuFind/Recommend/AbstractSearchObject.php
> +                $params->setSort($this->sort, true);
By default, you can only set sort to a value that's configured in searches.ini, but there are use cases where you might want to use a "hidden" sort value to give recommendations (e.g. you might not have a "sort by latest added to catalog" option in your searches.ini, but you might want to display recommendations based on a `first_indexed desc` sort).

2024-05-21 19:14 UTC, maccabeelevine commented on module/VuFind/src/VuFind/Recommend/AbstractSearchObject.php
> +                $params->setSort($this->sort, true);
Ok that definitely makes sense, thanks.

2024-05-21 19:26 UTC, demiankatz commented on config/vufind/searches.ini
> +;       for parameter definitions. Note that some may not apply to this search backend.
I've tested the EDS, EPF and Website modules and adjusted the documentation to reflect how things work. I can't test Summon but strongly suspect that my documentation there is correct. I also updated the LibGuides entries to indicate which things won't have any effect. Hopefully that makes this all more clear, though I'm open to further adjustments if you have suggestions.

2024-05-21 20:11 UTC, maccabeelevine commented on config/vufind/searches.ini
> +;       for parameter definitions. Note that some may not apply to this search backend.
Looks great now, and the comments also provide a pretty clear enhancement path if we feel the need.

2024-05-21 20:11 UTC, maccabeelevine approved these changes

2024-05-22 13:45 UTC, merged