updated setupJumpMenus from jquery to javascript
vufind-org/vufind pull request #3681
Opened 2024-05-21 16:22 UTC by padmasreegade

updated setupJumpMenus from jquery to vanilla javascript

2024-05-21 17:10 UTC, demiankatz requested changes
Thanks, @padmasreegade -- this looks pretty good to me, but I haven't tested it yet. One question before I dig in deeper...

2024-05-21 17:10 UTC, demiankatz commented on themes/bootstrap3/js/common.js
> +  var container = _container || document.body;
_container may be a jQuery object, based on usage in record.js. Should we add an unwrapJQuery() call somewhere to ensure things are consistent?

2024-05-23 22:10 UTC, demiankatz approved these changes
Thanks, @padmasreegade -- this looks good to me and all tests are passing. I'll wait to see if @crhallberg has any additional comments before merging.

2024-05-30 18:43 UTC, crhallberg approved these changes

2024-05-30 18:44 UTC, merged