[VUFIND-1697] NPM build:css task should auto-install dependencies
vufind-org/vufind pull request #3820
Opened 2024-07-01 18:10 UTC by demiankatz

This is probably not the most elegant solution to this problem, but it works for me...

TODO
- [ ] Close [VUFIND-1697](https://openlibraryfoundation.atlassian.net/browse/VUFIND-1697) when merging

2024-08-05 11:06 UTC, EreMaijala requested changes
I don't like it that this will hit npmjs.org on each run, so I think we need to at least add the `--no-audit` parameter to `npm install` in themes/bootstrap5/package.json. As far as I can see this would avoid hitting the server when everything is up to date.

2024-08-05 11:06 UTC, EreMaijala commented on package.json
> +    "build:scss-dependencies": "cd themes/bootstrap5 && npm i",
This should have `npm run installBuildDeps` instead of `npm i`.

2024-08-05 11:11 UTC, EreMaijala commented on package.json
>      "watch:scss": "grunt watch:scss",
Don't we need the the dependency check with these two as well?

2024-08-05 12:14 UTC, demiankatz commented
Thanks, @EreMaijala -- I've applied your review suggestions and have also renamed the new `build:scss-dependencies` to `install:scss-dependencies` since the `build` name wasn't really appropriate.

2024-08-06 07:45 UTC, EreMaijala approved these changes
Thanks, seems to work great now! What also nice with the current mechanism is that you can still run grunt directly to avoid going through the setup. Something worth keeping in mind if grunt is phased out at some point!

2024-08-06 12:01 UTC, merged