Fix KeepAlive error in trigger-print.js
vufind-org/vufind pull request #3863
Opened 2024-08-16 17:00 UTC by crhallberg

`trigger-print.js` was refactored 5 months ago to use a new mechanism to wait for the AJAX content for save status and availability. That mechanism should have replaced this previous waitForAjax method. This fixes that and cleans up the file.

2024-08-16 17:38 UTC, demiankatz requested changes
Looks like you need to run `vendor/bin/phing update-bootstrap5` to get the themes back in sync.

Should this be rebased on release-10.0 -- would you consider it a bug fix?

I'll be happy to run Mink tests on both bootstrap3 and bootstrap5 if that would be helpful, once things are updated.

2024-08-16 18:17 UTC, crhallberg commented
DONE and DONE

2024-08-16 19:43 UTC, demiankatz requested changes
Unfortunately, this is not working for me. When I try this in Firefox (by making sure `runningTestSuite=1` is removed from my config.ini, and by turning on `showBulkOptions`, then running a search, selecting all, and clicking Print) the printout I receive has "Loading..." values instead of the actual AJAX response data. Are you seeing otherwise in your environment?

(I'm using "Print to PDF" as my driver, so I can share output if that would be helpful).

2024-08-21 17:41 UTC, demiankatz approved these changes
Thanks, @crhallberg! I've resynchronized the files between the bootstrap3 and bootstrap5 themes, and this seems to work correctly in both places now.

2024-08-21 17:41 UTC, merged