Configurable favorite sort options
vufind-org/vufind pull request #3895
Opened 2024-08-29 09:46 UTC by ThoWagen

As discussed in #3884 this PR adds the possibility to configure the favorite list's sort options.

@demiankatz concerting your comment

> I wonder if the solution should involve a str_replace in one direction or the other (e.g. normalize spaces to underscores), so legacy inconsistent values continue to work. 

I added the alias `sort_year asc = "sort_year_asc"` so outdated configurations should still work.

Also, there are a lot of automatic cs fixes by my IDE included. Those are removing spaces at the end of lines and adding empty lines at the end of files. I figured that they might actually be an improvement. But please tell me if you don't want them and I will revert those changes.

2024-08-29 11:19 UTC, demiankatz requested changes
Thanks, @ThoWagen, I haven't tried this out yet, but it looks like it's off to a great start. One request regarding the config files, though...

2024-08-29 11:19 UTC, demiankatz commented on module/VuFind/tests/fixtures/configs/1.1/Summon.ini
> +PublicationDate:asc = sort_year_asc
The config files under fixtures are historical legacy configurations used for upgrade tests, and should not be changed. Do you mind reverting these few files?

Given that we no longer support upgrading from version 1 anyway, and I plan to remove the infrastructure supporting it in release 11, some of them may go away soon anyway.

2024-08-29 13:46 UTC, ThoWagen commented on module/VuFind/tests/fixtures/configs/1.1/Summon.ini
> +PublicationDate:asc = sort_year_asc
Sorry, I was not aware of that. I reverted the changes there. (Only the fixture files under 'configs/1.*' are legacy right?)

2024-08-29 15:02 UTC, demiankatz commented on module/VuFind/tests/fixtures/configs/1.1/Summon.ini
> +PublicationDate:asc = sort_year_asc
The worldcat fixture is also legacy (and will soon be deleted as well when the WorldCat v1 API is taken offline and all related code will need to be removed).

2024-08-30 09:53 UTC, ThoWagen commented on module/VuFind/tests/fixtures/configs/1.1/Summon.ini
> +PublicationDate:asc = sort_year_asc
done

2024-08-30 14:02 UTC, demiankatz approved these changes
Thanks, @ThoWagen, this looks good to me!

2024-08-30 14:02 UTC, merged