Preprocess query string before normalization
vufind-org/vufind pull request #3932
Opened 2024-09-11 09:54 UTC by ThoWagen

We want to use "DismaxMunge" to change freestanding plusses into something else. But currently that is not possible because freestanding plusses get removed by normalization before the dismax munge is applied. 

This PR changes the order of those operations.

2024-09-11 11:34 UTC, demiankatz requested changes
Thanks, @ThoWagen, this seems reasonable... but since the change doesn't break any existing tests, we must have a gap in coverage. Would it be feasible to add a test case to demonstrate the change in functionality?

2024-09-11 15:46 UTC, ThoWagen commented
@demiankatz Yes, I will add it tomorrow.

2024-09-12 07:49 UTC, ThoWagen commented
The test is added.

2024-09-12 19:48 UTC, demiankatz approved these changes
Thanks, @ThoWagen!

2024-09-12 19:48 UTC, merged