Ensure boundWithRecords is clear each time through the loop
vufind-org/vufind pull request #3936
Opened 2024-09-11 21:34 UTC by dltj

If a FOLIO instance has multiple items on one holding and only one of the items has bound-with information, the `$boundWithRecords` variable for subsequent items has that item's bound-with information.

2024-09-11 21:41 UTC, dltj commented
@maccabeelevine This completely goes against my understanding of variable scope, but unless I set this variable to null, subsequent runs through `foreach ($this->getPagedResults('items', '/inventory/items-by-holdings-id',$query) as $item) {...}` pick up the previous item's `boundWithTitles`. 
![image](https://github.com/user-attachments/assets/d68449aa-929f-4018-8a2e-49d7895dbefa)

2024-09-12 10:50 UTC, demiankatz requested changes
Good catch! This does make sense to me, though I've also requested a review from @maccabeelevine in case I'm somehow overlooking something. (I'm pretty sure I'm not, though :-) )

The issue is that [PHP variable scoping](https://www.php.net/manual/en/language.variables.scope.php) is less granular than in other languages like, for example, Javascript. In Javascript, every brace introduces a new variable scope, so this foreach loop would get fresh variables each iteration. But in PHP, there are really only two scopes: global and function-level. So the variables in the foreach loop persist across iterations because they are inside the same function.

One request, though, before merging this: since this is a pretty significant bug fix, can we rebase the PR against the release-10.0 branch and change the base of the PR? Should be possible with something like:

```
git checkout boundwith-multiple-items-bug
git reset --hard upstream/release-10.0
git cherry-pick aca8b2a979783474a32113bf74e8353ae165bf2e
git push --force
```

2024-09-12 11:35 UTC, maccabeelevine approved these changes
Nice catch @dltj !

2024-09-12 12:01 UTC, demiankatz approved these changes
Since @maccabeelevine has approved this, I went ahead and did the rebasing onto release-10.0. I'll merge this now!

2024-09-12 12:13 UTC, merged

2024-09-12 16:24 UTC, dltj commented
Thanks for the explanation about PHP variable scopes! That'll be handy information going forward, I'm sure. Also thanks for rebasing and merging.