Correct ARIA attributes on record and collection tabs.
vufind-org/vufind pull request #3978
Opened 2024-10-02 07:35 UTC by pasitiis

Fixed an issue where tabs did not work properly when using VoiceOver with Chrome and Firefox (issues with activating a tab using VO + Space Bar and aria-selected being read incorrectly). The changes aim to follow the ARIA Authoring Practices Guide pattern (https://www.w3.org/WAI/ARIA/apg/patterns/tabs/).

Changes were originally made to the BS5 theme and converted to BS3.

Tested with VO on Safari, Chrome, and Firefox, and with JAWS 2024 on Edge and Chrome.

Hopefully I didn't break anything when I converted the theme, and @EreMaijala  could check the impact of the bs3-compact changes.

2024-10-02 17:24 UTC, demiankatz commented
Thanks, @pasitiis. I'll wait to see what @EreMaijala has to say before digging too deeply.

@sturkel89, if time permits, do you mind running the test suite on this one and also manually checking whether the record tab behavior seems negatively impacted in any of the themes?

2024-10-03 18:18 UTC, sturkel89 approved these changes
I ran the complete test suite on this branch, and all tests passed!

I then updated config.ini with the full list of themes, and clicked through the record tabs (Holdings, Description, Comments, Similar Items, and Staff View) in each theme for a couple of different records. Everything worked normally!

Please let me know if there's any other functionality I should check with this PR.

2024-10-07 13:27 UTC, EreMaijala requested changes
I think we need `role="presentation"` for the li elements. Otherwise at least Axe doesn't like them. Other than that this looks good to me. Perhaps similar changes could be applied to search tabs as well.

2024-10-09 08:56 UTC, EreMaijala approved these changes
Thanks, everything checks out now!

2024-10-09 08:56 UTC, merged