classify eJournals as journals
vufind-org/vufind pull request #3981
Opened 2024-10-04 11:24 UTC by cx6ds

With this extension, eJournals are not classified as “Serial”, but as "Journal".

2024-10-07 16:48 UTC, demiankatz commented
Thanks, @cx6ds -- I'm going to consult with the cataloging team here to see if there are any concerns about this change. I'd also welcome input from others!

2024-10-08 10:07 UTC, demiankatz requested changes
After having some conversations with a cataloger here and with @EreMaijala in Slack, I think there might be a better/safer way to do this.

Our cataloger was concerned that if the leader is set to "computer file," the 008 field is not supposed to include journal data -- this approach seems like it may be targeting non-standards-compliant records.

@EreMaijala suggested that a safer solution might be to look at 008 position 23 for the 'o' value, similar to the eBook handling in lines 262-267 above your change. We could even establish an eJournal value so users could optionally distinguish between electronic/physical journals or else map both to the same Journal value to merge them together.

What do you think? Would that still work for your existing use case?

2024-10-16 14:44 UTC, cx6ds commented
Thank you @demiankatz and @EreMaijala for looking at it. Firstly, you have revealed that our MARC records are probably incorrectly coded at this point. And your suggestion with the subdivision of journal and eJournal or the possibility of mapping the two together is exactly the feature that is needed for our systems in the future. We would be delighted if this solution were to be included in the Vufind standard.

2024-10-16 14:54 UTC, demiankatz commented
@cx6ds, do you want to try to implement the proposed eJournal solution, or would it be helpful if one of us pushed some revisions to this PR? Or would you rather close this for now and open a new one after your investigations are completed on your end? Any of those options is fine with me -- I just want to find the best way to move the work forward. :-)

2024-10-22 09:58 UTC, cx6ds commented
We have introduced a new format type "eJournal" with the MARC characteristics proposed by @demiankatz and @EreMaijala. This is then mapped to "Journal" so that everything remains the same for all those who do not want to differentiate.

2024-10-22 12:16 UTC, demiankatz requested changes
Thanks, @cx6ds! A couple of suggestions:

2024-10-22 12:16 UTC, demiankatz commented on import/index_java/src/org/vufind/index/FormatCalculator.java
> +                } else if (recordType == 'm') {
Rather than being an `else if` would it be better for this to be a separate `if (recordType == 'a' || recordType == 'm') {` block, since I'm not sure if every eJournal is going to be flagged as a computer file, and checking 008/23==o is valid for both of those types?

2024-10-22 12:16 UTC, demiankatz commented on import/translation_maps/format_map.properties
> +eJournal            = Journal
We will also need to add new mappings for eJournal to format_map_level0.properties and format_map_level1.properties for the benefit of those using the hierarchical version of the format. I think it's probably okay to copy the existing Journal mappings for now for consistency/back-compatibility, though in future we may decide to differentiate them.

2024-10-24 07:58 UTC, cx6ds commented on import/index_java/src/org/vufind/index/FormatCalculator.java
> +                } else if (recordType == 'm') {
We like this more inclusive approach and have implemented it

2024-10-24 08:00 UTC, cx6ds commented on import/translation_maps/format_map.properties
> +eJournal            = Journal
We have tried to make "eJournal" completely analog to "Journal".

2024-10-24 18:51 UTC, demiankatz commented on import/translation_maps/format_map.properties
> +eJournal            = Journal
Thanks, I think that looks right!

2024-10-24 18:53 UTC, demiankatz commented
Since we're getting very close to the 10.1 release and I don't want to introduce any surprises at the last minute, I'm going to target this PR against the 11.0 milestone so there's time for me to review it one last time with the cataloging department here (and make sure @EreMaijala is also happy with its present form). Thanks for the ongoing work; I think we're nearly done!

2024-10-24 19:46 UTC, demiankatz requested changes
See below for a possible next revision; please let me know what you think!

2024-10-24 19:46 UTC, demiankatz commented on import/index_java/src/org/vufind/index/FormatCalculator.java
> +                    }
When I talked to one of our catalogers about this, he suggested that maybe the 008/21 case shouldn't take precedence over the 008/23 case in all situations. What if we changed this block to something like this?

```
            // Serial
            case 's':
                // For some materials, we may want to know if this is an online item:
                boolean isOnline = (recordType == 'a' || recordType == 'm') && (get008Value(marc008, 23) == 'o');
                // Look in 008 to determine what type of Continuing Resource
                // Make sure we have the applicable LDR/06: Language Material
                if (recordType == 'a') {
                    switch (get008Value(marc008, 21)) {
                        case 'n':
                            return "Newspaper";
                        case 'p':
                            return isOnline ? "eJournal" : "Journal";
                        default: break;
                    }
                } 
                // Default to serial even if 008 is missing (but use eJournal for online things)
                if (!isConferenceProceeding(record)) {
                    return isOnline ? "eJournal" : "Serial";
                }
                break;
```

I think that's a little more concise, and it also accounts for a bit more nuance.

2024-11-12 13:07 UTC, demiankatz approved these changes
Thanks, @cx6ds! I had to adjust one of our integration tests to account for the fact that the "Serial" format is now less likely to be used; now I believe this is ready to go!

2024-11-12 13:08 UTC, merged