BS5: Update icon aliases to accurate Font Awesome 6 classes
vufind-org/vufind pull request #4040
Opened 2024-10-25 20:35 UTC by crhallberg

MVP of https://github.com/vufind-org/vufind/pull/4031.

2024-10-28 13:11 UTC, demiankatz requested changes
@crhallberg, there seems to be a parse error in theme.config.php that's breaking the build.

Also, is there a reason you're removing the "FontAwesome" prefix from all of the icon configurations? This seems like it might be a problem.

Bottom line: I'm a bit concerned that this is a dangerous change to be making at the last minute. Could you clarify exactly which problem(s) it is addressing? Maybe there is a still smaller/safer fix we could make to address the issues....

2024-10-28 14:47 UTC, crhallberg commented
This is absolutely not a critical fix. I realized halfway through #4031 that the FA4 icons are being shimmed by FA6, so my fears about broken icons are unfounded. If we want to skip this until icon mixins are released, there shouldn't be any issues. Icon mixins would be an excellent addition when we bring together community themes for download and customization.

2024-10-28 15:25 UTC, demiankatz commented
Thanks, @crhallberg, if you think it best to just close this and wait for #4031, that's fine with me. Sorry if this wasted some of your time!

2025-01-15 19:41 UTC, crhallberg commented
No, I definitely wasted my own time lol.

2025-01-15 19:41 UTC, closed without merging