Fix issues with facet badges
vufind-org/vufind pull request #4057
Opened 2024-11-05 12:44 UTC by EreMaijala

- Count badges for checkbox facets were on wrong level and not right-aligned properly.
- Height and top settings in sandal and sandal5 caused misaligned numbers in badges.

2024-11-05 18:00 UTC, demiankatz requested changes
Merging other PRs created some conflicts here, which I have resolved for you to save time.

Just one question based on a code review; once that's answered, I'll take some time looking at this hands-on (and/or ask for @sturkel89's help).

2024-11-05 18:00 UTC, demiankatz commented on themes/bootstrap3/js/facets.js
> +            ? '.checkboxFilter ' : ':not(.checkbox-filter)';
This is quite confusing. Is it intentional that you're using `.checkboxFilter` in one case but `.checkbox-filter` in the other? If so, maybe a comment would be in order to clarify that.

I pondered whether introducing the `.checkbox-filters` class from #4058 early might help, but actually I'm not convinced that it would -- `.checkbox-filter` vs. `.checkbox-filters` also raises questions about whether there might be an accidental typo... so I think in either case, a comment here would be justified.

2024-11-05 18:57 UTC, EreMaijala commented on themes/bootstrap3/js/facets.js
> +            ? '.checkboxFilter ' : ':not(.checkbox-filter)';
True, that was a bit confusing. Now replaced with `.facet-group`, which also aligns nicely with #4058.

2024-11-05 19:49 UTC, demiankatz commented
@EreMaijala, the code looks good to me now, but I confess that I can't remember how to turn on counts in checkbox facets to test! Is that only supported by certain backends? Can you refresh my memory? I wonder if some improved documentation in the .ini files is needed too, if this is just a setting that I couldn't find...

2024-11-06 07:51 UTC, EreMaijala commented
> @EreMaijala, the code looks good to me now, but I confess that I can't remember how to turn on counts in checkbox facets to test! Is that only supported by certain backends? Can you refresh my memory? I wonder if some improved documentation in the .ini files is needed too, if this is just a setting that I couldn't find...

It's not possible without customization at the moment, but I think I can provide another PR to enable them.

2024-11-06 08:24 UTC, EreMaijala commented
@demiankatz Meanwhile the easiest way to test this is to hack \VuFind\AjaxHandler\GetSideFacets::getCheckboxFacetCount to:
```
    protected function getCheckboxFacetCount($facet, Results $results)
    {
        return rand(0, 100000);
    }

```

2024-11-07 15:38 UTC, demiankatz approved these changes
Thanks, @EreMaijala, looks good to me now!

2024-11-07 15:38 UTC, merged