Fix implicitly nullable arguments.
vufind-org/vufind pull request #4140
Opened 2024-12-05 10:46 UTC by EreMaijala

This is part one of improving PHP 8.4 compatibility.

2024-12-05 18:09 UTC, demiankatz requested changes
Thanks for the monumental effort, @EreMaijala. I don't think it's possible to edit 575 files without missing a few details, though; see below for some notes. I've tried to use the GitHub suggest feature where possible (sadly, not as many places as I would like), so hopefully you can make at least a few fixes by just clicking a button instead of editing yourself.

In any case, all tests are passing for me, and the vast majority of these issues are just related to comments (though there are a couple that may be more significant).

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFind/ILS/Driver/Folio.php
> +     * @param array    $options Extra options (not currently used)
This got formatted incorrectly for some reason; fix:

```suggestion
     * @param string $bibId   Bib-level id
     * @param ?array $patron  Patron login information from $this->patronLogin
     * @param array  $options Extra options (not currently used)
```

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFind/Record/Loader.php
> +        ?ParamBag $params = null
Comment above needs to be adjusted to match.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFind/Record/Loader.php
> +        ?ParamBag $params = null
Same here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFind/Reserves/CsvReader.php
> +        while ($line = fgetcsv($fh, 0, $this->delimiter, escape: '\\')) {
This appears to be an accidental change unrelated to the rest of this PR.

```suggestion
        while ($line = fgetcsv($fh, 0, $this->delimiter)) {
```

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFind/Reserves/CsvReader.php
> +        while ($line = fgetcsv($fh, 0, $this->delimiter, escape: '\\')) {
This appears to be an accidental change unrelated to the rest of this PR.

```suggestion
        while ($line = fgetcsv($fh, 0, $this->delimiter)) {
```

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFind/Search/Solr/InjectSpellingListener.php
> +        ?LoggerInterface $logger = null
Comment needs to be adjusted to match.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFind/Solr/Writer.php
> +        ?ParamBag $params = null
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFindTest/Container/MockContainer.php
> +    public function build($name, ?array $options = null)
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFindTest/Feature/MockSearchCommandTrait.php
> +        ?ParamBag $params = null,
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
> +        ?int $timeout = null
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
> +        ?int $timeout = null
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/src/VuFindTest/Integration/MinkTestCase.php
> +        ?int $timeout = null
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/integration-tests/src/VuFindTest/Mink/SearchLimitTest.php
> +        ?string $options = null,
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Auth/ILSAuthenticatorTest.php
> +        ?EmailAuthenticator $emailAuth = null,
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Recommend/SideFacetsTest.php
> +        ?\Laminas\Stdlib\Parameters $request = null
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Record/LoaderTest.php
> +        ?FallbackLoader $fallbackLoader = null
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/RecordDriver/SolrOverdriveTest.php
> +        ?OverdriveConnector $connector = null
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/RecordTab/TabManagerTest.php
> +        ?ConfigManager $configManager = null
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Search/EDS/ParamsTest.php
> +        ?PluginManager $mockConfig = null
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Search/HistoryTest.php
> +        ?\VuFind\Config\Config $config = null
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ParamsTest.php
> +        ?PluginManager $mockConfig = null
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ResultsTest.php
> +        ?Loader $loader = null
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Search/Solr/ResultsTest.php
> +        ?PluginManager $mockConfig = null
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/Search/Summon/ParamsTest.php
> +        ?PluginManager $mockConfig = null
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/IconTest.php
> +        ?StorageInterface $cache = null,
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordTest.php
> +        ?Context $context = null,
Comments need adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFind/tests/unit-tests/src/VuFindTest/View/Helper/Root/RecordTest.php
> +        ?\VuFindHttp\HttpService $httpService = null,
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Import/WebCrawlCommandTest.php
> +        ?Config $config = null,
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Language/AddUsingTemplateCommandTest.php
> +        ?ExtendedIniReader $reader = null,
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Language/CopyStringCommandTest.php
> +        ?ExtendedIniReader $reader = null,
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Language/DeleteCommandTest.php
> +        ?ExtendedIniReader $reader = null,
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindConsole/tests/unit-tests/src/VuFindTest/Command/Util/CreateHierarchyTreesCommandTest.php
> +        ?PluginManager $results = null
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/BackendInterface.php
> +        ?ParamBag $params = null
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/BackendInterface.php
> +    public function retrieve($id, ?ParamBag $params = null);
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Blender/Backend.php
> +        ?ParamBag $params = null
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Blender/Backend.php
> +    public function retrieve($id, ?ParamBag $params = null)
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/BrowZine/Backend.php
> +        ?ParamBag $params = null
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/BrowZine/Backend.php
> +    public function retrieve($id, ?ParamBag $params = null)
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/EDS/Backend.php
> +        ?ParamBag $params = null
Comment needs adjustment.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/EDS/Backend.php
> +    public function retrieve($id, ?ParamBag $params = null)
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/EIT/Backend.php
> +     * @param ?RecordCollectionFactoryInterface $factory   Record collection factory (null for default)
Code below has not been updated. Is this change actually needed here?

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/EIT/Backend.php
> +        ?ParamBag $params = null
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/EIT/Backend.php
> +    public function retrieve($id, ?ParamBag $params = null)
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/EIT/Connector.php
> +    public function getRecord($id, ?ParamBag $params = null)
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Exception/DeepPagingException.php
> +        ?Exception $prev = null
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/LibGuides/Backend.php
> +        ?ParamBag $params = null
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/LibGuides/Backend.php
> +    public function retrieve($id, ?ParamBag $params = null)
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Pazpar2/Backend.php
> +        ?ParamBag $params = null
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Pazpar2/Backend.php
> +    public function retrieve($id, ?ParamBag $params = null)
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Primo/Backend.php
> +        ?ParamBag $params = null
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Primo/Backend.php
> +    public function retrieve($id, ?ParamBag $params = null)
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Solr/Backend.php
> +        ?ParamBag $params = null
Comment needs to be updated (here and in most changes below as well).

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php
> +    public function retrieve($id, ?ParamBag $params = null)
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Solr/Connector.php
> +        ?ParamBag $params = null
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/Summon/Backend.php
> +        ?ParamBag $params = null
Comment needs to be updated (here and in two places below).

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/WorldCat2/Backend.php
> +        ?ParamBag $params = null
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Backend/WorldCat2/Backend.php
> +    public function retrieve($id, ?ParamBag $params = null)
...and here.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Feature/GetIdsInterface.php
> +        ?ParamBag $params = null
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Feature/RandomInterface.php
> +        ?ParamBag $params = null
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Feature/RetrieveBatchInterface.php
> +    public function retrieveBatch($ids, ?ParamBag $params = null);
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/src/VuFindSearch/Feature/SimilarInterface.php
> +    public function similar($id, ?ParamBag $params = null);
Comment needs to be updated.

2024-12-05 18:09 UTC, demiankatz commented on module/VuFindSearch/tests/unit-tests/src/VuFindTest/Backend/Blender/BackendTest.php
> +        ?Query $query = null
Comment needs to be updated.

2024-12-09 09:40 UTC, EreMaijala commented
@demiankatz Thanks for thorough checks! I believe I've now addresses the doc comments listed as well as some others I noticed. I'm sure there are still issues with doc comments in methods untouched here, but I couldn't find a great way to ensure consistency.

2024-12-09 14:03 UTC, demiankatz approved these changes
Thanks, @EreMaijala! In double-checking everything, I found two more minor mismatched comments, which I just went ahead and fixed. Should be safe to merge this now!

2024-12-09 14:03 UTC, merged